version: '1'
services:
  multi-bot-wordsplitter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080
    env:
      # Port configuration
      - name: PORT
        value: 8080
      
      # SHARED Configuration for ALL bots
      - name: OWNER_IDS
        description: "Comma-separated Telegram user IDs for ALL bot owners"
      - name: ALLOWED_USERS
        description: "Comma-separated allowed user IDs for ALL bots"
      - name: WEBHOOK_URL_BASE
        description: "Base webhook URL for ALL bots (e.g., https://yourserver.com)"
      
      # SHARED Performance limits for ALL bots
      - name: MAX_QUEUE_PER_USER
        value: "5"
      - name: MAX_MSG_PER_SECOND
        value: "30"
      - name: MAX_CONCURRENT_WORKERS
        value: "15"
      
      # Bot A specific (token and db only)
      - name: TELEGRAM_TOKEN_A
        description: "Telegram Bot Token for Bot A from @BotFather"
        secret: true
      - name: DB_PATH_A
        value: "/tmp/botdata_a.sqlite3"
      
      # Bot B specific (token and db only)
      - name: TELEGRAM_TOKEN_B
        description: "Telegram Bot Token for Bot B from @BotFather"
        secret: true
      - name: DB_PATH_B
        value: "/tmp/botdata_b.sqlite3"
      
      # Bot C specific (token and db only)
      - name: TELEGRAM_TOKEN_C
        description: "Telegram Bot Token for Bot C from @BotFather"
        secret: true
      - name: DB_PATH_C
        value: "/tmp/botdata_c.sqlite3"
      
      # Shared settings for all bots
      - name: REQUESTS_TIMEOUT
        value: "10"
      - name: LOG_RETENTION_DAYS
        value: "30"
      - name: FAILURE_NOTIFY_THRESHOLD
        value: "6"
      - name: PERMANENT_SUSPEND_DAYS
        value: "365"
    
    resources:
      memory: 512Mi  # Increased for 3 bots
      cpu: 500m      # Increased for 3 bots
    healthCheck:
      # Multiple health endpoints available, using bot A as main health check
      path: /health/a
      port: 8080
      initialDelay: 10
      period: 30
    autoscale:
      enabled: false
    domains:
      - host: multi-bot-wordsplitter
        paths:
          - /
