version: '1'
services:
  multi-bot-wordsplitter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080
    env:
      # Port configuration
      - name: PORT
        value: 8080
      
      # Webhook base URL
      - name: WEBHOOK_URL_BASE
        description: "Base URL for webhooks (e.g., https://yourserver.com)"
      
      # Shared user management
      - name: OWNER_IDS
        description: "Comma-separated Telegram user IDs for bot owners (e.g., 123456789,987654321)"
      - name: ALLOWED_USERS
        description: "Comma-separated allowed user IDs for all bots"
      - name: OWNER_TAG
        value: "Owner (@justmemmy)"
      
      # Bot-specific Telegram tokens
      - name: TELEGRAM_TOKEN_A
        description: "Telegram Bot Token for Bot A from @BotFather"
        secret: true
      - name: TELEGRAM_TOKEN_B
        description: "Telegram Bot Token for Bot B from @BotFather"
        secret: true
      - name: TELEGRAM_TOKEN_C
        description: "Telegram Bot Token for Bot C from @BotFather"
        secret: true
      
      # Bot-specific interval speeds
      - name: INTERVAL_SPEED_A
        value: "fast"
      - name: INTERVAL_SPEED_B
        value: "fast"
      - name: INTERVAL_SPEED_C
        value: "slow"
      
      # Database template (bot-specific paths generated from template)
      - name: DB_PATH_TEMPLATE
        value: "/tmp/botdata_{bot_id}.sqlite3"
      
      # Shared operational settings (same for all bots)
      - name: MAX_QUEUE_PER_USER
        value: "5"
      - name: MAX_MSG_PER_SECOND
        value: "30"
      - name: MAX_CONCURRENT_WORKERS
        value: "15"
      
      # Shared timeout and retention settings
      - name: REQUESTS_TIMEOUT
        value: "10"
      - name: LOG_RETENTION_DAYS
        value: "30"
      - name: FAILURE_NOTIFY_THRESHOLD
        value: "6"
      - name: PERMANENT_SUSPEND_DAYS
        value: "365"
    
    resources:
      memory: 512Mi  # Increased for 3 bots
      cpu: 500m      # Increased for 3 bots
    healthCheck:
      # Multiple health endpoints available, using bot A as main health check
      path: /health/a
      port: 8080
      initialDelay: 10
      period: 30
    autoscale:
      enabled: false
    domains:
      - host: multi-bot-wordsplitter
        paths:
          - /
